### ISSUE TITLE
Food101 model

### ISSUE THREAD

**Issue by ph1ps** [likedan/Awesome-CoreML-Models#15]
Sorry that I don't conform to your issue guide but my issue is just to improve an already existing model in your collection. 

I saw that you added images with the input types and the output types of each model to your README and I therefore wanted to tell you that I finally converted the Food101 CoreML model in a matter where it now accepts `CVPixelBuffer` instead of `MLMultiArray` as an input.

Just a little update :)

**Comment by likedan** [comment]
Awesome! Can you send me a link of the new model File? I’ll update it. 
And btw, we’re working on an interface so you can manage the model version and content yourself.

**Comment by likedan** [comment]
I found the model file from your repo. Updated.👍

**Comment by ph1ps** [comment]
@likedan Cool! Thank you.

**Comment by ph1ps** [comment]
@likedan Sorry if I confused you but the original reason of this issue was just to correct this to `Image` since I made an update to correct this in my model.

![screenshot](https://user-images.githubusercontent.com/5064728/31054268-77eb0a9e-a6af-11e7-8981-74904be12839.png)

**Comment by likedan** [comment]
It has been already updated in the resource, let me fix this.
