### ISSUE TITLE
Nudity model

### ISSUE THREAD

**Issue by ph1ps** [likedan/Awesome-CoreML-Models#16]
## License
BSD-2

## Summary
This model detects nudity and it's score from an image. The original dataset is Yahoo's OpenNSFW.

## Model URL
Since this is too big for Github I have a GoogleDrive link:
https://drive.google.com/open?id=0B5TjkH3njRqncDJpdDB1Tkl2S2s

## Demo URL
https://github.com/ph1ps/Nudity-CoreML

## Samples
Input: <img src="https://user-images.githubusercontent.com/5064728/31111397-0ebf9ae8-a80e-11e7-9214-e41a08849bf6.jpg" width="100" /> Output: SFW (100%), NSFW (0%)
Input: Image, Output: NSFW (80%), SFW(20%)

This gives you back both NSFW and SFW score in order to make people able to decide what their personal threshold is. Let's say there is a picture with NSFW - 70%, some people might consider this as safe but others not. Therefore they can say everything from 70% and down is SFW and everything from 71% to 100% is NSFW.

## Checklist

- [x] Only one item is in this issue
- [x] The model info contains all the required fields
- [x] The demo project is compilable
- [x] Has proper reference
- [x] If this model takes image as input, an image type is selected instead of multiarray
      (See https://developer.apple.com/wwdc17/710 if you don't know how to do this)

**Comment by likedan** [comment]
@ph1ps For the samples input image, can you add the link to the actual image? The best is to have one nudity image and one non nudity image so people easily see how the model works.

**Comment by ph1ps** [comment]
@likedan Sorry but I'm not able to upload a nude picture on Github since it would violate the community guidelines.

**Comment by likedan** [comment]
😹. Yep. I'll pick an appropriate picture for this
