### ISSUE TITLE
NamesDT

### ISSUE THREAD

**Issue by alexcurylo** [likedan/Awesome-CoreML-Models#17]
(not [the author](http://nlpforhackers.io), just stumbled across this and seems it would fit in Text Analysis here)

## License

MIT

## Summary

A Demo application using CoreML framework for predicting gender from first names.
See [Is it a boy or a girl? An introduction to Machine Learning](http://nlpforhackers.io/introduction-machine-learning/)

## Model URL

> [CoreML model](https://github.com/cocoa-ai/NamesCoreMLDemo/blob/master/Names/Resources/NamesDT.mlmodel) was converted from Scikit-learn Pipeline using coremltools python package.

## Demo URL

[NamesCoreMLDemo](https://github.com/cocoa-ai/NamesCoreMLDemo)

## Samples

In demo README

## Checklist

- [x] Only one item is in this issue
- [x] The model info contains all the required fields
- [x] The demo project is compilable
- [x] Has proper reference

**Comment by likedan** [comment]
Thanks for contributing! Just verified that the model works. Will close the issue once I added it to the list.

**Comment by likedan** [comment]
Added!
