### ISSUE TITLE
How to convert Tensorflow models to CoreML model?

### ISSUE THREAD

**Issue by bibekdari** [likedan/Awesome-CoreML-Models#18]

**Comment by likedan** [comment]
As far as I know, no one have implemented such library yet.

**Comment by Deano123** [comment]
No-one has in 4 days? Uh, kinda strange don't you think!!

**Comment by likedan** [comment]
There's people calling for that since the first day CoreML came out. I think there might be some technical challenge in building a converter from Tensorflow to Core ML, otherwise someone or Apple itself might just have done it. Thoughts?

**Comment by likedan** [comment]
There's Tensorflow Lite which works with iOS. That might be a workaround.

**Comment by devajith** [comment]
you can try this :
https://github.com/tf-coreml/tf-coreml
but it has some limitations.

**Comment by igor9silva** [comment]
CoreML Tools can achieve that (official tool from Apple). See https://pypi.python.org/pypi/coremltools.
