### ISSUE TITLE
New Model: DocumentClassification

### ISSUE THREAD

**Issue by toddkramer** [likedan/Awesome-CoreML-Models#19]
This model is also included in an open-source [framework](https://github.com/toddkramer/DocumentClassifier) that can be used for document classification.

## License
MIT

## Summary
- Classifies documents into one of five categories (Business, Entertainment, Politics, Sports, Technology)
- Trained with 1,500 articles from the BBC. See "References" in [README](https://github.com/toddkramer/DocumentClassifier/blob/master/README.md)

## Model URL
[Model Link](https://github.com/toddkramer/DocumentClassifier/blob/master/Sources/DocumentClassification.mlmodel)

## Demo URL
Demo app is the NewsClassifier iOS app [here](https://github.com/toddkramer/DocumentClassifier)

## Samples
Screenshot from the demo app [here](https://github.com/toddkramer/DocumentClassifier/blob/master/NewsClassifier/Screenshot.png)

## Checklist
- [x] Only one item is in this issue
- [x] The model info contains all the required fields
- [x] The demo project is compilable
- [x] Has proper reference
- [x] If this model takes image as input, an image type is selected instead of multiarray
      (See https://developer.apple.com/wwdc17/710 if you don't know how to do this)

**Comment by likedan** [comment]
This is great! Will add.

**Comment by toddkramer** [comment]
Awesome thanks!

**Comment by likedan** [comment]
Added. Thanks for contributing!

**Comment by toddkramer** [comment]
Thanks again!
