### ISSUE TITLE
New Model: Fast-Style-Transfer

### ISSUE THREAD

**Issue by mdramos** [likedan/Awesome-CoreML-Models#21]
## License

My Code is MIT, though the model  requires an agreement for commercial use
## Summary

I implemented Fast Style Transfer in CoreML. This is similar to Fast Neural Style, but is TensorFlow. 
My article explains the process.
## Model URL

https://github.com/lengstrom/fast-style-transfer
## Demo URL

https://medium.com/@rambossa/diy-prisma-fast-style-transfer-app-with-coreml-and-tensorflow-817c3b90dacd
https://github.com/mdramos/fast-style-transfer-coreml

## Samples

Here are some CoreML models I created in the process: https://drive.google.com/drive/folders/1CBSanBHbXC5-bJNTTk3-r1WSq56z0eKG?usp=sharing
-- just include these in the ios app before running
## Checklist

- [x] Only one item is in this issue
- [x] The model info contains all the required fields
- [x] The demo project is compilable  (AFTER INCLUDE THE MLMODELS)
- [?] Has proper reference
- [x] If this model takes image as input, an image type is selected instead of multiarray
      (See https://developer.apple.com/wwdc17/710 if you don't know how to do this)

**Comment by likedan** [comment]
Yo. The demo looks very similar to https://github.com/prisma-ai/torch2coreml. I'm not sure how much it's interrelated but maybe you should cite it?
There are new models so I'll take this!

**Comment by mdramos** [comment]
Hey it’s sited in my blog post, and I state that I use Prismas approach—
but I’ll add the same to the repo. Very similar for sure. But mine uses the
TensorFlow approach (a lot of people have been trying to convert this to
CoreMl) by Logan Engstrom, where as Prisma demonstrates converting the
Torch model by Justin Johnson.

Thanks!!

**Comment by likedan** [comment]
Now I see the difference. Great work!

**Comment by devajith** [comment]
will you able to convert this style transfer model :
https://github.com/vanhuyz/CycleGAN-TensorFlow/releases/download/v0.1-alpha/apple2orange.pb

**Comment by mdramos** [comment]
@devajith it looks like that graph has cycles, so probably not (at least not easily)
