### ISSUE TITLE
Traffic Sign Detection Benchmark

### ISSUE THREAD

**Issue by ihyildiz** [likedan/Awesome-CoreML-Models#23]
This model should detect and recognize live video traffic signs. If there is a speed limit fo example the app should detect and recognize this shield.

There is a lot of sources...

## Model URL
http://btsd.ethz.ch/shareddata/
http://benchmark.ini.rub.de/?section=gtsdb&subsection=news

## Demo URL
http://www.vision.ee.ethz.ch/~timofter/

**Comment by likedan** [comment]
Hi, thanks for submitting!

Do you have a demo that's in CoreML format, preferably runnable with Xcode?

**Comment by sufak** [comment]
Hi, yes i do, Thanks!

________________________________
Gönderen: Kedan Li <notifications@github.com>
Gönderildi: 6 Mart 2018 Salı 02:04
Kime: likedan/Awesome-CoreML-Models
Bilgi: Subscribed
Konu: Re: [likedan/Awesome-CoreML-Models] Traffic Sign Detection Benchmark (#23)


Hi, thanks for submitting!

Do you have a demo that's in CoreML format, preferably runnable with Xcode?

**Comment by ihyildiz** [comment]
Hi, yes…I have it.

Am 06.03.2018 um 00:04 schrieb Kedan Li <notifications@github.com<mailto:notifications@github.com>>:


Hi, thanks for submitting!

Do you have a demo that's in CoreML format, preferably runnable with Xcode?

**Comment by likedan** [comment]
Could you point me to where that is? I haven't found it from the original links you posted.

**Comment by ihyildiz** [comment]
I have implemented by myself. I can sen you an zip file.

Hakki

Von meinem iPhone gesendet

Am 07.03.2018 um 18:55 schrieb Kedan Li <notifications@github.com<mailto:notifications@github.com>>:


Could you point me to where that is? I haven't found it from the original links you posted.

**Comment by likedan** [comment]
Yeah. That would be great! Or push it into a public repo. I think people will want to see that

**Comment by chinmay5** [comment]
Is the model already pushed in the repo. I could not find it
