### ISSUE TITLE
I don't see any model for lowercase/uppercase text recognition (printed text... not handwritten) and digits. 

### ISSUE THREAD

**Issue by sergiobuonanno** [likedan/Awesome-CoreML-Models#25]
## Checklist

- [ ] Only one item is in this issue
- [ ] The model info contains all the required fields
- [ ] The demo project is compilable
- [ ] Has proper reference
- [ ] If this model takes image as input, an image type is selected instead of multiarray
      (See https://developer.apple.com/wwdc17/710 if you don't know how to do this)

**Comment by likedan** [comment]
Yeah, it would be great if someone can do that. Shouldn't be hard
