### ISSUE TITLE
New Model: PoseEstimation

### ISSUE THREAD

**Issue by tucan9389** [likedan/Awesome-CoreML-Models#27]
## License
Apache License 2.0

## Summary
[edvardHua](https://github.com/edvardHua) implements [PoseEstimationForMobile](https://github.com/edvardHua/PoseEstimationForMobile) estimating human pose from a picture for mobile. And I make [demo](https://github.com/tucan9389/PoseEstimation-CoreML) for that on iOS.
- Estimate human pose
- Train AI Challenger dataset that is single person image dataset contain about 20,000
## Model URL
[Model URL](https://github.com/edvardHua/PoseEstimationForMobile/tree/master/release)

## Demo URL
[Demo URL](https://github.com/tucan9389/PoseEstimation-CoreML)

### Input
Image[URL]

### Output
Heatmap[Array<Array<Array<Float>>>]

model |cpm|hourglass
-----|-----|-----
output | [96, 96, 14] | [48, 48, 14]

## Checklist

- [x] Only one item is in this issue
- [x] The model info contains all the required fields
- [x] The demo project is compilable
- [x] Has proper reference
- [x] If this model takes image as input, an image type is selected instead of multiarray
      (See https://developer.apple.com/wwdc17/710 if you don't know how to do this)

**Comment by tucan9389** [comment]
@likedan Hi again and Happy new year! Could you check this proposal? :) I had forgotten until yesterday.

**Comment by likedan** [comment]
Sorry it took so long. Our AWS account is broken, has to revert to old format.
