### ISSUE TITLE
All links leads to dead website coreml.store

### ISSUE THREAD

**Issue by 0x384c0** [likedan/Awesome-CoreML-Models#29]
https://downforeveryoneorjustme.com/coreml.store
Is this project still alive?

**Comment by likedan** [comment]
The AWS account hosting it got suspended. Trying to fix it.

**Comment by vinitra** [comment]
@likedan It seems like coreml.store is still down! Is that correct?

**Comment by likedan** [comment]
Yeah. Having trouble reclaim the AWS account. sorry!
