### ISSUE TITLE
fyi - GAN

### ISSUE THREAD

**Issue by johndpope** [likedan/Awesome-CoreML-Models#3]
https://github.com/zedge/DynamicCoreML

**Comment by likedan** [comment]
@johndpope  This looks cool! Feel free to create a PR and I'll add it to the page.

**Comment by likedan** [comment]
@johndpope I just took a closer look at it, it's not a new model but a potentially useful tool for Core ML. We might want to add a section, something like CoreML Tools, to list this kind of resources.
