### ISSUE TITLE
New Model:NIMA

### ISSUE THREAD

**Issue by yulingtianxia** [likedan/Awesome-CoreML-Models#30]
## License
MIT

## Summary
Automatically learned quality assessment for images has recently become a hot topic due to its usefulness in a wide variety of applications such as evaluating image capture pipelines, storage techniques and sharing media. Despite the subjective nature of this problem, most existing methods only predict the mean opinion score provided by datasets such as AVA [1] and TID2013 [2]. Our approach differs from others in that we predict the distribution of human opinion scores using a convolutional neural network. Our architecture also has the advantage of being significantly simpler than other methods with comparable performance. Our proposed approach relies on the success (and retraining) of proven, state-of-the-art deep object recognition networks. Our resulting network can be used to not only score images reliably and with high correlation to human perception, but also to assist with adaptation and optimization of photo editing/enhancement algorithms in a photographic pipeline. All this is done without need for a "golden" reference image, consequently allowing for single-image, semantic- and perceptually-aware, no-reference quality assessment.

## Model URL
[Model Link](https://github.com/yulingtianxia/PhotoAssessment/blob/master/PhotoAssessment-Sample/Sources/NIMANasnet.mlmodel)

## Demo URL
[PhotoAssessment](https://github.com/yulingtianxia/PhotoAssessment)

## Samples
Input: Image[http://i1.hdslb.com/bfs/archive/9892e6f032425fc9e9831fa1ed855318c12702ad.jpg], Output: Double 10 vector [1.614268398952845e-06,0.0006238522473722696,0.02812075242400169,0.2070262581110001,0.3266536593437195,0.332121878862381,0.09285952150821686,0.01259173825383186,2.718873588491988e-07,4.697789393048879e-07]

## Checklist
- [x] Only one item is in this issue
- [x] The model info contains all the required fields
- [x] The demo project is compilable
- [x] Has proper reference
- [x] If this model takes image as input, an image type is selected instead of multiarray

**Comment by likedan** [comment]
Sorry it took so long. Our AWS account is broken, has to revert to old format.
